<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<style>
.errorResponseForgotPassword.success {
    color: green;
    margin: 10px 0;
}
.errorResponseForgotPassword.error {
    color: red;
    margin: 10px 0;
}
</style>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/forgotpasswordpost',['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <div class="forgotTp_Bx">
	<fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <h2>Forgot Your Password?</h2>
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
		<div class="errorResponseForgotPassword"></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="E-mail Address" >
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Send Password Reset Link')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
	</div>
</form>
<div class="forgotBtm_Bx">
	<div class="forgetpasswordDivider">OR</div>
	<div>
		<button onclick="PodiumWebChat.open();"><span><?= $block->escapeHtml(__('Click to SMS our Support Team')) ?></span></button>
	</div>
</div>
<script>
		require([
			'jquery',
			'mage/mage',
			'jquery/validate',
		], function($){
		
		
		
		$('.form.password.forget:visible').submit(function(e){
			e.preventDefault();
			console.log('submit prevented');
			$( ".errorResponseForgotPassword" ).html('');
			if($('.form.password.forget:visible input[name="email"]').val()==""){
					return false;
			}
			if($('.form.password.forget:visible').find('.mage-error:visible').length > 0){
				return false;
			}
			
			
			var formData =  getFormData(jQuery('.form.password.forget:visible'));
			$.ajax({
				url: "<?= $block->escapeUrl($block->getUrl('customerlogin/ajax/forgotpassword')) ?>", 
				data:formData,
				type: 'POST',
				dataType: 'json',
				beforeSend: function() {
					jQuery('body').loader('show');
					// show some loading icon
				},
				success: function(data, status, xhr) {
					console.log(data);
					console.log(data.errors);
					
					if(data.errors == false){
						$( ".errorResponseForgotPassword" ).addClass( 'success' );
						$( ".errorResponseForgotPassword" ).removeClass( 'error' );
						$('.errorResponseForgotPassword').html(data.message);
						setTimeout(function(){
							if(data.redirectUrl){
								window.location.href = data.redirectUrl;
							}else{
									//window.location.reload();
									
							}
							
						},500);
						
					}else{
						$( ".errorResponseForgotPassword" ).addClass( 'error' );
						$( ".errorResponseForgotPassword" ).removeClass( 'success' );
						$('.errorResponseForgotPassword').html(data.message);
						return false;
					}
					// data contains your controller response
				},
				error: function (xhr, status, errorThrown) {
					console.log('Error happens. Try again.');
					console.log(errorThrown);
				},
				complete:function(){
					jQuery('body').loader('hide');
				}
				});
			});
		
		});
	</script>