<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<style>
.errorResponse.success {
    color: green;
    margin: 10px 0;
}
.errorResponse.error {
    color: red;
    margin: 10px 0;
}
</style>
<div class="block block-customer-login">
    <div class="block-title mooon">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Log In')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login login-form-popup"
              action="<?= $block->escapeUrl($block->getUrl('customerlogin/ajax/login')) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
			 <input type="hidden" name="redirect_url" value="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
				<div class="errorResponse"></div>
                <div class="field email required">
                    <div class="control">
                       <!-- <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="Email" required> -->
					   <input name="username" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="Email" required> 
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <!-- <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" placeholder="Password" required> -->
						  <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" placeholder="Password" required>
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
					<button type="submit" class="action login primary customer-login-trigger" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div id="jaybro_forgetpasswordTrigger" class="secondary"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></div>
                    
                </div>
            </fieldset>
        </form>
		<script>
		require([
			'jquery',
			'mage/mage',
			'jquery/validate',
		], function($){
		
		$(document).ready(function(){
			if(window.location.href.includes('customer/account/login')==true){
				$(".moon_popUp_login").addClass('fadeIn');
				$("body").addClass('hiddenScrollPopUp');
				$(".moon_popUp_signup").removeClass('fadeIn');
			}
		});
		
		//$(document).on("click",".customer-login-trigger",function(e){
			$('.login-form-popup:visible').submit(function(e){
				e.preventDefault();
				console.log('submit prevented');
			$( ".errorResponse" ).html('');
			
			
			
			if($('.login-form-popup:visible input[name="username"]').val()=="" || $('.login-form-popup:visible input[name="username"]').val()==""){
			
					return false;
			}
			if($('.login-form-popup:visible').find('.mage-error:visible').length > 0){
				return false;
			}
			
			$.ajax({
				url: "<?= $block->escapeUrl($block->getUrl('customerlogin/ajax/login')) ?>", 
				data: {"form_key": $('.login-form-popup input[name="form_key"]').val(), "redirect_url": $('.login-form-popup input[name="redirect_url"]').val(), "username": $('.login-form-popup:visible input[name="username"]').val(), "password": $('.login-form-popup:visible input[name="password"]').val()},
				type: 'POST',
				dataType: 'json',
				beforeSend: function() {
					$('body').loader('show');
					// show some loading icon
				},
				success: function(data, status, xhr) {
					console.log(data);
					console.log(data.errors);
					
					if(data.errors == false){
						$( ".errorResponse" ).addClass( 'success' );
						$( ".errorResponse" ).removeClass( 'error' );
						$('.errorResponse').html(data.message);
						setTimeout(function(){
							if(data.redirectUrl){
								window.location.href = data.redirectUrl;
							}else{
									window.location.reload();
							}
							
						},500)
						
					}else{
						$( ".errorResponse" ).addClass( 'error' );
						$( ".errorResponse" ).removeClass( 'success' );
						$('.errorResponse').html(data.message);
						return false;
					}
					// data contains your controller response
				},
				error: function (xhr, status, errorThrown) {
					console.log('Error happens. Try again.');
					console.log(errorThrown);
				},
				complete:function(){
					$('body').loader('hide');
				}
				});
			});
		
		});
	</script>
		<?php
		
		echo $this->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('create_account_bottom')
		->toHtml();
		
		?>
   
        </div>
    </div>

</div>
