<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $custom_class = 'href="'.$block->getBaseUrl().'customer/account/logout/"';
} else {
    $custom_class = 'data-toggle="modal" data-target="#login-modal"';
}
?>
<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?> login-popup">
    <span class="fa fa-user" id="user-icon"></span>
    <a <?php /* @noEscape */ /*$block->getLinkAttributes()*/ ?><?= /* @noEscape */ $dataPostParam ?> <?= /* @noEscape */ $custom_class ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
