<div class="about-us-container">
    <div class="aboutus-navigation">
            <div class="mobile-toggle-btn">About us</div>
            <ul class="navigation-aboutus">
                <li class="about"><a href="/about">About Us</a></li>
                <li class="our-purpose"><a href="/about/our-purpose">Purpose</a></li>
                <li class="jom"><a href="/about/jom">JOM</a></li>
                <li class="our-culture"><a href="/about/our-culture">Culture</a></li>
                <li class="our-people"><a href="/about/our-people">People</a></li>
                <li class="nps"><a href="/about/nps">NPS</a></li>
                <li class="capabilities-brands"><a href="/about/capabilities-brands">Capabilities and Brands</a></li>
                <li class="sustainability"><a href="/about/sustainability">Sustainability</a></li>
                <li class="our-history"><a href="/about/our-history">History</a></li>
                <li class="careers"><a href="/about/careers">Careers</a></li>
            </ul>
        </div>
    </div>
</div>