<header>
    <div id="custom-header-id"class="header page-main">
        <div class="row no-margin">
            <div class="col-md-2 col-sm-3 col-xs-5 custom-logo">
                <?php echo $this->getChildHtml("logo"); ?>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-7 mobile-link">
                <?php echo $this->getChildHtml('minicart'); ?>
                <?php echo $this->getChildHtml("topSearch"); ?>
                <?php echo $this->getChildHtml("headerPanel"); ?>
            </div>
        </div>
    </div>
</header>