<div class="container">
   <div class="row footer-links">
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <ul>
                <li><h3>About Jaybro</h3></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about"> About Us </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/our-purpose/">Our Mission </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/our-culture/">Diversity </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/nps/"> Testimonials </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/careers/"> Careers </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/contact-us/"> Contact Us </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/blog.html/"> The Jaybro Blog </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <ul>
                <li><h3>Customer Support</h3></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/jaybro-catalogue/"> Request a Catalogue </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/retractions-recalls-corrections/"> Retractions </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/30-day-trade-account/"> Credit Application </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/jaybro-policies/"> Terms &amp; Conditions </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/shipping/"> Shipping </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/used-concrete-barriers-for-sale/"> Used Concrete Barriers </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>/about/book-now/">Respirator Fit Testing</a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <ul>
                <li><h3>My Account</h3></li>
                <li><a href="https://www.jaybro.com.au/customer/account/"> My Account </a></li>
                <li><a href="https://www.jaybro.com.au/amasty_quote/account/index/"> My Quote </a></li>
                <li><a class="jaybro_forgetpasswordTrigger" href="https://www.jaybro.com.au/#/"> Forgotten Password </a></li>
                <li><a href="https://www.jaybro.com.au/about/price-beat/"> Request a Price Beat</a></li>
                <li><a href="https://www.jaybro.com.au/weekly-special/clearance.html/"> Stock Clearance </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <ul>
                <li><h3>Contact Info</h3></li>
                <li class="jaybro-email"><span class="fa fa-envelope"></span> sales@jaybro.com.au</li>
                <li class="jaybro-phone"><span class="fa fa-phone"></span> 1300 885 364</li>
                <li><p>Guaranteed Secure Transaction Online</p></li>
            </ul>
       </div>
   </div>
</div>