<div class="container">
   <div class="row footer-links">
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="about-jaybro">About Jaybro <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="about-jaybro">
                <li><a href="<?php $block->getBaseUrl(); ?>about"> About Us </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/our-purpose/">Our Mission </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/our-culture/">Diversity </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/nps/"> Testimonials </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/careers/"> Careers </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>contact-us/"> Contact Us </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>blog.html/"> The Jaybro Blog </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="customer-support">Customer Support <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="customer-support">
                <li><a href="<?php $block->getBaseUrl(); ?>jaybro-catalogue/"> Request a Catalogue </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>retractions-recalls-corrections/"> Retractions </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/30-day-trade-account/"> Credit Application </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>jaybro-policies/"> Terms &amp; Conditions </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/shipping/"> Shipping </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/used-concrete-barriers-for-sale/"> Used Concrete Barriers </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/book-now/">Respirator Fit Testing</a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="my-account">My Account <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="my-account">
                <li><a data-label="login-popup" data-toggle="modal" data-target="#login-modal" style="cursor: pointer;"> My Account </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>amasty_quote/account/index/"> My Quote </a></li>
                <li><a class="jaybro_forgetpasswordTrigger" data-dismiss="modal" data-toggle="modal" data-target="#forgot-password-modal" style="cursor: pointer"> Forgotten Password </a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>about/price-beat/"> Request a Price Beat</a></li>
                <li><a href="<?php $block->getBaseUrl(); ?>weekly-special/clearance.html/"> Stock Clearance </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="contact-info">Contact Info <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="contact-info">
                <li class="jaybro-email"><span class="fa fa-envelope"></span> sales@jaybro.com.au</li>
                <li class="jaybro-phone"><span class="fa fa-phone"></span> 1300 885 364</li>
                <li><p>Guaranteed Secure Transaction Online</p></li>
            </ul>
       </div>
   </div>
</div>