<div class="container">
   <div class="row footer-links">
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="about-jaybro">About Jaybro <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="about-jaybro">
                <li><a href="/about"> About Us </a></li>
                <li><a href="/about/our-purpose/">Our Mission </a></li>
                <li><a href="/about/our-culture/">Diversity </a></li>
                <li><a href="/about/nps/"> Testimonials </a></li>
                <li><a href="/about/careers/"> Careers </a></li>
                <li><a href="/contact-us/"> Contact Us </a></li>
                <li><a href="/blog.html/"> The Jaybro Blog </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="customer-support">Customer Support <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="customer-support">
                <li><a href="/jaybro-catalogue/"> Request a Catalogue </a></li>
                <li><a href="/retractions-recalls-corrections/"> Retractions </a></li>
                <li><a href="/about/30-day-trade-account/"> Credit Application </a></li>
                <li><a href="/jaybro-policies/"> Terms &amp; Conditions </a></li>
                <li><a href="/about/shipping/"> Shipping </a></li>
                <li><a href="/about/used-concrete-barriers-for-sale/"> Used Concrete Barriers </a></li>
                <li><a href="/about/book-now/">Respirator Fit Testing</a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="my-account">My Account <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="my-account">
                <li><a data-label="login-popup" data-toggle="modal" data-target="#login-modal" style="cursor: pointer;"> My Account </a></li>
                <li><a href="/amasty_quote/account/index/"> My Quote </a></li>
                <li><a class="jaybro_forgetpasswordTrigger" data-dismiss="modal" data-toggle="modal" data-target="#forgot-password-modal" style="cursor: pointer"> Forgotten Password </a></li>
                <li><a href="/about/price-beat/"> Request a Price Beat</a></li>
                <li><a href="/weekly-special/clearance/"> Stock Clearance </a></li>
            </ul>
       </div>
       <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-container">
            <h3 class="contact-info">Contact Info <span class="fa fa-angle-right pull-right"></span></h3>
            <ul class="contact-info">
                <li class="jaybro-email"><span class="fa fa-envelope"></span> sales@jaybro.com.au</li>
                <li class="jaybro-phone"><span class="fa fa-phone"></span> 1300 885 364</li>
                <li>
                    <div class="guayanteedSec">
                        <p>Guaranteed Secure <br>Transaction Online</p>
                        <p><!-- Begin eWAY Linking Code --></p>
                        <div id="eWAYBlock">
                        <div style="text-align: center;"><a title="eWAY Payment Gateway" href="https://www.eway.com.au/secure-site-seal?i=12&amp;se=7&amp;theme=1" target="_blank" rel="nofollow noopener"> <img src="https://www.eway.com.au/developer/payment-code/verified-seal.php?img=12&amp;size=7&amp;theme=1" alt="eWAY Payment Gateway"> </a></div>
                        </div>
                        <!-- End eWAY Linking Code -->
                    </div>
                </li>
            </ul>
       </div>
   </div>
</div>