<div class="footer-bottom-container">
    <div class="row footer-bottom">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 footer-logo">
            <a href="/"><img src="/media/wysiwyg/Jaybro-logo_-_Copy_1.png" alt="" /></a>
        </div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 copyright-container">
            <p>© 2021 The Jaybro Group. All Rights Reserved. <a href="/disclaimers" class="disclaimer">Disclaimer</a> | <a href="/privacy" class="privacy">Privacy</a></p>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 social-icons-container">
            <p><span class="follow-us">Follow Us</span><a href="https://www.facebook.com/jaybroaustralia/"><span class="fa fa-facebook-square"></span></a><a href="https://www.linkedin.com/company/jaybro-civil-&-safety-products/"><span class="fa fa-linkedin-square"></span></a><a href="https://www.instagram.com/jaybrogroup/"><span class="fa fa-instagram"></span></a><a href="https://www.youtube.com/channel/UCdOIZCqeF-7qvlitqiffgLw"><span class="fa fa-youtube-play"></span></a></p>
        </div>
    </div>
</div>