<div class="footer-newsletter">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
                <h2>Get our weekly Wacky Wednesday Deals!</h2>
                <form class="form subscribe moon" novalidate="novalidate" action="https://www.jaybro.com.au/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
                    <div class="form-group">
                        <input name="firstname" type="text" id="firstname" placeholder="Name" data-validate="{required:true}">
                    </div>
                    <div class="form-group">
                        <input name="email" type="email" id="newsletter" placeholder="Email" data-validate="{required:true, 'validate-email':true}">
                    </div>
                    <button class="action subscribe primary" title="Submit" type="submit">
                        <span>Submit</span>
                    </button>
                </form>
            </div>

        </div>
    </div>
</div>