<div class="container-fluid footer-bottom-container">
    <div class="row footer-bottom">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <p>Jaybro Logo</p>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 copyright-container">
            <p>© 2021 The Jaybro Group. All Rights Reserved. <a class="disclaimer">Disclaimer</a> | <a class="privacy">Privacy</a></p>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 social-icons-container">
            <p><span class="follow-us">Follow Us</span><span class="fa fa-facebook-square"></span><span class="fa fa-linkedin-square"></span><span class="fa fa-instagram"></span><span class="fa fa-youtube-play"></span></p>
        </div>
    </div>
</div>