
<!-- Forgot password Modal -->
<div class="modal fade" id="forgot-password-modal" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="border-bottom: 0px;">
          <button type="button" class="close" data-dismiss="modal">X</button>
          <div class="header-forgot-password text-center">
            <h1 class="modal-title"><span class="fa fa-user"></span>Forgot Your Password?</h1>
            <p>Please enter your email address below to receive a password reset link.</p>
          </div>
        </div>
        <div class="modal-body">
           <div class="row">
              <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 text-center col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
                <form action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
                  method="post"
                  id="form-validate"
                  data-mage-init='{"validation":{}}'>
                  <div class="form-group">
                    <input name="email" value="" autocomplete="off" id="email" type="email" class="input-text" title="Email" data-validate="{required:true, 'validate-email':true}" placeholder="E-mail Address" required="" aria-required="true">
                  </div>
                  <div class="row actions-toolbar">
                      <button type="submit" class="btn-forgot-password">Send Password Reset Link</button>
                  </div>
                </form>
              </div>
           </div>
        </div>
        <div class="forgot-password-divider">OR</div>
        <div class="modal-footer" style="border-top: 0px;">
          <div class="modal-footer-description">
             <div class="row text-center">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 image-icon-container">
                  <img src="https://www.jaybro.com.au/pub/media/wysiwyg/forgotIconBtm.png" width="100" height="100" />
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 sms-container">
                  <button type="button" class="btn-sms-support-team">Click To SMS Our Support Team</button>
                </div>
             </div>
          </div>
        </div>
      </div>
      
    </div>
</div>