<!-- Modal -->
<div class="modal fade" id="login-modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="border-bottom: 0px;">
          <button type="button" class="close" data-dismiss="modal">X</button>
          <div class="header-login">
            <h1 class="modal-title"><span class="fa fa-user"></span>Login</h1>
            <p>If you have an account, sign in with your email address.</p>
          </div>
        </div>
        <div class="modal-body">
          <form action="/action_page.php">
            <div class="form-group">
              <input name="username" value="" autocomplete="off" id="email" type="email" class="input-text" title="Email" data-validate="{required:true, 'validate-email':true}" placeholder="Email" required="" aria-required="true">
            </div>
            <div class="form-group">
              <input name="password" type="password" autocomplete="off" class="input-text" id="password" title="Password" data-validate="{required:true}" placeholder="Password" required="" aria-required="true">
            </div>
            <div class="row actions-toolbar">
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                  <p class="forgot-password">Forgot Your Password? </p>
               </div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                  <button class="btn-signin">Sign In</button>
               </div>
            </div>
          </form>
        </div>
        <div class="modal-footer" style="border-top: 0px;">
          <div class="modal-footer-description">
            <h2><span class="fa fa-user-plus"></span> Create an Account</h2>
            <ul class="create-account-description">
              <li><span class="fa fa-check"></span> Reduced pricing on a wide range of products</li>
              <li><span class="fa fa-check"></span> 5% price beat guarantee</li>
              <li><span class="fa fa-check"></span> 4 hour metro delivery</li>
            </ul>
          </div>
          <button type="button" class="btn btn-default btn-register" data-dismiss="modal">Register Now</button>
        </div>
      </div>
      
    </div>
</div>