<!-- Signin Modal -->
<div class="modal fade" id="login-modal" role="dialog">
    <div class="modal-dialog">
    <form action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="border-bottom: 0px;">
          <button type="button" class="close" data-dismiss="modal">X</button>
          <div class="header-login">
            <h1 class="modal-title"><span class="fa fa-user"></span>Login</h1>
            <p>If you have an account, sign in with your email address.</p>
          </div>
        </div>
        <div class="modal-body">
            <div class="form-group">
              <?= $block->getBlockHtml('formkey') ?>
              <input name="login[username]" value="" autocomplete="off" id="email" type="email" class="input-text" title="Email" data-validate="{required:true, 'validate-email':true}" placeholder="Email" required="" aria-required="true">
            </div>
            <div class="form-group">
              <input name="login[password]" type="password" autocomplete="off" class="input-text" id="password" title="Password" data-validate="{required:true}" placeholder="Password" required="" aria-required="true">
            </div>
            <div class="row actions-toolbar">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 recaptcha">
                <div class="g-recaptcha" data-sitekey="6LcLUL4dAAAAABA-cbJjMDOX6ZFlWbrPiYG0GyO9
"></div>
               </div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                  <a class="forgot-password" data-dismiss="modal" data-toggle="modal" data-target="#forgot-password-modal">Forgot Your Password? </a>
               </div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                  <input type="button" class="btn-signin" value="Signin" />
               </div>
            </div>
        </div>
        <div class="modal-footer" style="border-top: 0px;">
          <div class="modal-footer-description">
            <h2><span class="fa fa-user-plus"></span> Create an Account</h2>
            <ul class="create-account-description">
              <li><span class="fa fa-check"></span> Reduced pricing on a wide range of products</li>
              <li><span class="fa fa-check"></span> 5% price beat guarantee</li>
              <li><span class="fa fa-check"></span> 4 hour metro delivery</li>
            </ul>
          </div>
          <button type="submit" class="btn btn-default btn-register" data-dismiss="modal" data-toggle="modal" data-target="#create-account-modal">Register Now</button>
        </div>
      </div>
      </form>
    </div>
</div>