<!-- Create Account Modal -->
<div class="modal fade" id="create-account-modal" role="dialog">
    <div class="modal-dialog">
    <form action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="border-bottom: 0px;">
          <button type="button" class="close" data-dismiss="modal">X</button>
          <div class="header-create-account">
            <h1 class="modal-title"><span class="fa fa-user"></span>CREATE AN ACCOUNT</h1>
            <p>By creating an account with our store, you will be able
to move through the checkout process faster.</p>
          </div>
        </div>
        <div class="modal-body">
            <fieldset class="fieldset create info">
                <legend class="legend"><span>Personal Information</span></legend><br>
                <input type="hidden" name="success_url" value="">
                <input type="hidden" name="error_url" value="">
                
                <!-- <div class="field field-name-firstname required" style="float: left;margin-right: 16px;"> -->
                <div class="form-group">
                    <input type="text" id="firstname" name="firstname" value="" title="First Name" placeholder="First Name*" required="" class="input-text required-entry" data-validate="{required:true}">
                </div>
                <div class="form-group">
                    <input type="text" id="lastname" name="lastname" value="" title="Last Name" placeholder="Last Name*" required="" class="input-text required-entry" data-validate="{required:true}">
                </div>
            </fieldset>
            <fieldset class="fieldset create info">
                <legend class="legend"><span>Login Information</span></legend><br>
                <div class="form-group">
                    <input type="email" name="email" autocomplete="email" id="email_address" value="" title="Email" class="input-text" data-validate="{required:true, 'validate-email':true}" placeholder="E-mail*" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" id="password" title="Password" class="input-text password" data-password-min-length="8" data-password-min-character-sets="3" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off" placeholder="Password*" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password_confirmation" title="Confirm Password" id="password-confirmation" class="input-text password" data-validate="{required:true, equalTo:'#password'}" autocomplete="off" placeholder="Confirm Password*" required="">
                </div>
            </fieldset>
            <div class="checkbox">
                <label><input type="checkbox" checked> Sign-up for Newsletter
            </label>
            </div>
        </div>
        <div class="modal-footer" style="border-top: 0px;">
          <button type="submit" class="btn btn-default btn-register">Create An Account</button>
        </div>
      </div>
      </form>
    </div>
</div>