<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getBaseUrl(); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("Our Range")?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('about'); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("About Jaybro")?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('careers'); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("Careers")?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('contact-us'); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("Contact Us")?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('my-quote'); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("My Quote")?></span>
    </a>
</li>