<div class="websiteswitcher">
    <div class="switcher website switcher-website" id="switcher-website">
            <div class="actions options switcher-options">
                <div class="action toggle switcher-trigger dropdown-toggle" role="button" tabindex="0" data-toggle="dropdown" data-trigger-keypress-button="true" id="switcher-website-trigger" aria-haspopup="true" aria-expanded="false">
                    <!-- img class="selectedflag" src ="https://www.jaybro.com.au/pub/static/frontend/Jaybro/luma_child/en_AU/images/flags/flag_au_base.gif" / --> 
                    <strong><span>AU Website</span></strong>
                </div>
                <label>Region: </label>
                <ul class="switcher-dropdown dropdown-menu" data-target="dropdown" aria-hidden="true">
			        <li class="switcher-option">
				        <a href="https://www.jaybro.co.nz/">
					    <!-- img src ="https://www.jaybro.com.au/pub/static/frontend/Jaybro/luma_child/en_AU/images/flags/flag_nz_base.gif" class="flaglist" / --> 
					    NZ Website</a>
			        </li>
                </ul>
            </div>
    </div>
</div>