<div class="main-container items-center" style="background-position:top center;background-repeat:no-repeat;background-size:cover;position:relative;opacity:0.99">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1 class="font-hairline text-2xl md:text-3xl mb-5 text-center">WE ARE A DIGITAL AGENCY SPECIALIZING IN ONLINE COMMERCE SOLUTIONS</h1>
                <p class="mb-5 text-center">Our Focus Is Improving Customer Engagement, and Increase Sales.</p>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 bg-brown text-center magento-migrate">
            <div class="mb-5 icon-logo-container">
                <img src="https://cdn.sanity.io/images/v32r25bv/production/427d66c689cc2820014a0d8e76e42afc682b713b-259x300.png?fm=webp" class="img-responsive" />
            </div>
            <h3 style="font-size:26px" class="text-white">MAGENTO 2 MIGRATE</h3>
            <hr class="w-24 border border-2 border-white" />
            <p class="text-white mb-10">Using modern tools and technologies, Magento 2 is more flexible, open and more compatible than any other  eCommerce platforms.</p>
            <div class="text-center">
                <a href="/magento-2-migration"><button class="bg-green text-white text-sm md:text-base font-bold rounded-md px-4 md:px-8 md:text-base w-full transition duration-300 ease-in-out  transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding-top:15px;padding-bottom:15px;width: 70%;font-weight: 700;">LEARN MORE!</button></a>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 bg-orange text-center magento-support">
            <div class="mb-5 icon-logo-container">
                <img src="https://cdn.sanity.io/images/v32r25bv/production/f6276517c02b69a7425349fb0f8badaa84e47fc3-259x300.png?fm=webp" class="img-responsive" />
            </div>
            <h3 style="font-size:26px" class="text-white">MAGENTO SUPPORT</h3>
            <hr class="w-24 border border-2 border-white" />
            <p class="text-white mb-10">We have a dedicated US based support staff that is focused on providing high-quality Magento Support to resolve your issues quickly and correctly.</p>
            <div class="text-center">
                <button class="bg-brown text-white text-sm md:text-base font-bold rounded-md px-4 md:px-8 md:text-base w-full transition duration-300 ease-in-out  transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding-top:15px;padding-bottom:15px;width: 70%;font-weight: 700;">LEARN MORE!</button>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 bg-brown text-center shopify-support text-white">
            <div class="mb-5 icon-logo-container">
                <img src="https://cdn.sanity.io/images/v32r25bv/production/76fbd08caad1ff317d89f6a271342a9ab25cbca5-259x300.png?fm=webp" class="img-responsive" />
            </div>
            <h3 style="font-size:26px" class="text-white">SHOPIFY SUPPORT</h3>
            <hr class="w-24 border border-2 border-white" />
            <p class="text-white mb-10">Are you just starting with Shopify and need some basic help, or have you been running your store for years and need some custom work done?</p>
            <div class="text-center">
                <button class="bg-green text-white text-sm md:text-base font-bold rounded-md px-4 md:px-8 md:text-base w-full transition duration-300 ease-in-out  transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding-top:15px;padding-bottom:15px;width: 70%;font-weight: 700;">LEARN MORE!</button>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row my-25">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <h2 class="mb-5 text-2xl">WHEN IT COME TO ECOMMERECE, WE ARE MAGENTO &amp; SHOPIFY EXPERTS</h2>
            <div class="w-110px border border-2 border-green mb-5"></div>
            <p>We have experience building and supporting over 500+ Magento Enterprise, Community &amp; Shopify sites.<br><br>Our clients range from small mom and pop stores to large international clients with thousands of visitors an hour.<br><br>We have been in business over 8 years consistently delivering excellent customer support.</p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <ul class="ul-list">
               <li><i class="fa fa-angle-right"></i> <span>Increase Sales</span></li>
               <li><i class="fa fa-angle-right"></i> <span>Track & Report Marketing</span></li>
               <li><i class="fa fa-angle-right"></i> <span>Improve Deeper Engagement</span></li>
               <li><i class="fa fa-angle-right"></i> <span>Custom Features</span></li>
               <li><i class="fa fa-angle-right"></i> <span>Fast Customer Support</span></li>
            </ul>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center" style="margin-top:30px;">
            <a href="/shopify-support"><button class="bg-green text-white text-sm md:text-base font-bold rounded-md px-4 md:px-8 md:text-base w-full transition duration-300 ease-in-out  transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding-top:15px;padding-bottom:15px;width: 30%;font-weight: bold">ABOUT US!</button></a>
        </div>
    </div>
</div>
<div class="bg-orange">
    <div class="bg-orange-background-image" style="background-position:left;background-repeat:no-repeat;background-size:cover;position:relative;opacity:0.99;z-index: 1;">
    <div class="container">
        <div class="row lg:py-28">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <h2 class="mb-6 text-2xl font-hairline text-white">WEBSITES THAT DRIVE RESULTS</h2>
                    <div class="w-110px border mx-auto md:mx-0 border-2 border-white mb-6"></div>
                    <p class="text-white">Websites should drive leads, sales, and deeper engagement. Websites are more than pretty brochures.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 website-design-container">
                    <a href="/website-design"><button class="bg-brown text-white text-sm md:text-base font-bold rounded-md px-4 md:px-8 md:text-base w-full transition duration-300 ease-in-out  transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding-top:15px;padding-bottom:15px;width: 50%;font-weight: bold;">WEBSITE DESIGN</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container our-clients">
    <div class="row my-20 lg:my-40">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
            <h2 class="mb-6 text-2xl">OUR CLIENTS</h2>
            <hr class="w-110px border border-2 border-green mb-6" />
            <p>Driving Sales for Leading Brands</p>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
            <div class="flex -mb-20 flex-col md:flex-row our-clients-icon-container">
                <div class="our-clients-icon">
                    <img src="https://cdn.sanity.io/images/v32r25bv/production/3040afd4fbd6c7ec6a90d2e21ec394a1bcb56431-300x300.png?w=160&amp;h=160&amp;fit=crop" style="margin:0;margin-left:10px" alt="brand logo">
                </div>
                <div class="our-clients-icon">
                    <img src="https://cdn.sanity.io/images/v32r25bv/production/e4bfba31b18dfcab0d7901c4f2f23e126cabbd3b-300x300.png?w=160&amp;h=160&amp;fit=crop" style="margin:0" alt="brand logo">
                </div>
                <div class="our-clients-icon">
                    <img src="https://cdn.sanity.io/images/v32r25bv/production/4e2e97e866b7b3fac0ca42f74fb9a465a33bc2fa-300x300.png?w=160&amp;h=160&amp;fit=crop" style="margin:0" alt="brand logo">
                </div>
                <div class="our-clients-icon">
                    <img src="https://cdn.sanity.io/images/v32r25bv/production/1d83ddff1d78b86bb77b20a5dc4aebd3761919e4-300x300.png?w=160&amp;h=160&amp;fit=crop" style="margin:0" alt="brand logo">
                </div>
                <div class="our-clients-icon">
                    <img src="https://cdn.sanity.io/images/v32r25bv/production/5a40561178a8b0886b4bf618b6c0b12ecdecffc7-300x300.png?w=160&amp;h=160&amp;fit=crop" style="margin:0;margin-top:10px;margin-left:10px" alt="brand logo">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="happy-customers" style="background-color:#f2f2f2">
    <div class="container">
        <div class="row my-20 lg:my-40">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                <h2 class="mb-6 text-2xl">HAPPY CUSTOMERS TELL GREAT STORIES</h2>
                <hr class="w-110px border border-2 border-green mb-6" />
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center">
                <h2 class="text-4xl text-green font-medium">11</h2>
                <p class="font-hairline" style="font-size:19px;line-height:2.5">Years In Business</p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center">
                <h2 class="text-4xl text-green">700+</h2>
                <p class="font-hairline" style="font-size:19px;line-height:2.5">Clients Served</p>
            </div>
        </div>
    </div>
</div>
<div class="contact-form" style="background-color:#473528;">
    <div class="container">
        <div class="row my-20 lg:my-40">
            <form name="contact_form" class="contact-form" method="post" action="/thank-you">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Name*" />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="business_name" name="business_name" placeholder="Busness Name*" />
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Email*">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Phone Number*" />
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <textarea class="mb-5 rounded w-full min-h-25" rows="4" style="padding:6px 16px" placeholder="Message*" name="message" spellcheck="false"></textarea>
                        <button class=" bg-orange text-white font-bold rounded-md w-full transition duration-300 ease-in-out transform hover:scale-110 hover:bg-lightgreen leading-none  " style="padding:15px 30px;font-weight: bold;width: 100%;border: 0px;" type="submit">SUBMIT</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>