<div class="main-container items-center" style="background-position:top center;background-repeat:no-repeat;background-size:cover;position:relative;opacity:0.99">
    <div class="container">
    <h1 class="font-hairline text-2xl md:text-3xl mb-5 text-center">WE ARE A DIGITAL AGENCY SPECIALIZING IN ONLINE COMMERCE SOLUTIONS</h1>
    <p class="mb-5 text-center">Our Focus Is Improving Customer Engagement, and Increase Sales.</p>
    </div>
</div>