<div class="footer parallax">
    <div class="container">
        <div class="row my-20 lg:my-40">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Logo%21_Logo.svg/800px-Logo%21_Logo.svg.png" class="img-responsive logo">
                <p class="text-white">Orange Collar Inc. is based in Denver, CO. We believe in delivering total solutions to our clients from design to support.</p>
                <div class="social-icons">
                    <a href="https://www.facebook.com/OrangeCollarInc/">
                        <span class="fa fa-facebook-square fa-3x"></span>
                    </a>
                    <a href="https://twitter.com/orangecollar">
                        <span class="fa fa-twitter-square fa-3x"></span>
                    </a>
                    <a href="https://www.linkedin.com/company/orange-collar-media/about/">
                        <span class="fa fa-linkedin-square fa-3x"></span>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <h3 class="text-xl mb-2 md:mb-3 text-white">SERVICES</h3>
                <ul>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="<?php $block->getBaseUrl(); ?>/magento-support/">Magento Support</a>
                    </li>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="<?php $block->getBaseUrl(); ?>/shopify-support/">Shopify Support</a>
                    </li>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="<?php $block->getBaseUrl(); ?>/website-design/">Website Design</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <h3 class="text-xl mb-2 md:mb-3 text-white">DESIGN AGENCY</h3>
                <ul>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="<?php $block->getBaseUrl(); ?>/blog/">Blog</a>
                    </li>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="<?php $block->getBaseUrl(); ?>/about/">About</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <h3 class="text-xl mb-2 md:mb-3 text-white">CONTACT US</h3>
                <ul>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="tel:18662621517">866-262-1517</a>
                    </li>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">hello@orangecollarmedia.com</li>
                    <li class="no-underline mb-2 duration-300 transition-all hover:text-green" style="box-shadow:none">
                        <a href="https://goo.gl/maps/VxfBfPz1ch2G2J8cA">1630 Welton St. #940</a>
                        <br>
                        <a href="https://goo.gl/maps/VxfBfPz1ch2G2J8cA">Denver, CO 80202</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="copyright-container text-center">
                    <p class="text-center text-white mt-8 text-center">2009 – 2020 © ORANGE COLLAR MEDIA​</p>
                </div>
            </div>
        </div>
    </div>
</div>