<div class="container">
    <div class="row home-slider-box">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <h4 class="w_heading "><span><img src="https://www.jaybro.com.au/pub/media/resized/50x50/5%20percent%20icon.png" width="50" height="50" /></span> <a href="https://www.jaybro.com.au/about/price-beat">Price Beat Guarantee</a></h4>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <h4 class="w_heading "><span><img src="https://www.jaybro.com.au/pub/media/resized/50x50/homePage/Metro-delivery.png" width="50" height="50" /></span> <a href="https://www.jaybro.com.au/about/shipping">4 Hour Metro Delivery</a></h4>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <h4 class="w_heading "><span><img src="https://www.jaybro.com.au/pub/media/resized/50x50/homePage/Instant-Messaging.png" width="50" height="50" /></span> <a href="https://www.jaybro.com.au/about/contact-us">Instant Messaging</a></a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <h4 class="w_heading "><span><img src="https://www.jaybro.com.au/pub/media/resized/50x50/no%20backorders%20icon.jpg" width="50" height="50" /></span> <a href="https://www.jaybro.com.au/about/our-mission">No Backorders</a></h4>
        </div>
    </div>
    <div class="row">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
            <div class="item active">
                <img src="https://www.jaybro.com.au/pub/media/solwin/bannerslider/b/p/bp2w_banners_web_2200x350.png" alt="Los Angeles" style="width:100%;">
            </div>

            <div class="item">
                <img src="https://www.jaybro.com.au/pub/media/solwin/bannerslider/b/p/bp2w_banners_web_2200x350.png" alt="Chicago" style="width:100%;">
            </div>
            
            <div class="item">
                <img src="https://www.jaybro.com.au/pub/media/solwin/bannerslider/b/p/bp2w_banners_web_2200x350.png" alt="New york" style="width:100%;">
            </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="fa fa-chevron-left"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="fa fa-chevron-right"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="row categories">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/civil-consumables-tile.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/underground-civil.html"><span>Civil Consumables</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/tools-and-ardware.jpg" class="img-responsive"  />
            </div>
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/tools-hardware-chemicals.html"><span>Tools, Hardware, Chemicals</span></a>
            </div> 
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/fortress.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/fortress-fencing-barriers.html"><span>Fortress Fencing & Barriers</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/traffic.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/"><span>Road Signs & Traffic</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/pffsigns.jpg" class="img-responsive"  />
            </div> 
            <div class="col-lg-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/signs-tags-labels-banners.html"><span>Printed Fabric & Safety Signs</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/geo.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/geosynthetics-drainage.html"><span>Geosynthetics & Drainage</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/safety-ppe.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/personal-protection-equipment.html"><span>Safety, PPE & Confined Space</span></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 image-item-container">
            <div class="image-item">
                <img src="https://www.jaybro.com.au/pub/media/resized/634x442/resized/634x442/homePage/workwear.jpg" class="img-responsive"  />
            </div> 
            <div class="col-md-12">
                <a class="category-link" title="Image" href="https://www.jaybro.com.au/personal-protection-equipment/workwear.html"><span>Workwear & Clothing</span></a>
            </div>
        </div>
    </div>
    <div class="row product-slider-container">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p>Show product slider</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
           <h2 class="w_heading jomeBlogHeading ">Latest Posts</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <h2 class="why-choose-jaybro">Why Choose Jaybro</h2>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h3 class="why-choose-jaybro-sub">Specialists in site consumables and safety.</h3>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 whyChooseJaybroText">
            <p>Jaybro is Australia and New Zealand's leading supplier to the civil construction and infrastructure sector. We're available when you are, opening the oﬃce early so you can call at the beginning of your day.</p>
            <p>Our team is made up of friendly, helpful staﬀ with knowledge you can rely on. We are big enough to manage huge orders and small enough to care about your business!</p>
            <p>We deliver where other companies don't, providing same-day delivery to sites, 4 hour delivery to metro areas, and producing special custom signs overnight. We connect you with our knowledgeable, experienced customer service and sales team who will help you get the best products at excellent prices. </p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 whyChooseJaybroText">
            <p>From supplying hundreds of thousands of gloves for major infrastructure projects, right through to shipping one-off orders with a smile, we service a wide range of businesses across Australia and New Zealand. Our team strives to wow our customers with service, from sole traders right through to the biggest construction giants.</p>
            <p>For more than two decades, Jaybro has been the name to remember for everything site consumables. From civil contractors to commercial construction companies, infrastructure projects, road and traffic contractors and the mining and resources industry, we help connect everyone with the equipment they need, when and where they need it.</p>
        </div>
    </div>
    <div class="row promo-image-container">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 BtmTwoBxLetf">
            <div class="col-inner">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="padding: 0px;">
                    <div class="image-item">
                        <img data-defaultsrc="https://www.jaybro.com.au/pub/media/resized/648x685/blog_images/Cashflow-Banner-Photo.jpg" data-imagetsrc="https://www.jaybro.com.au/pub/media/blog_images/Cashflow-Banner-Photo.jpg" data-smallsrc="https://www.jaybro.com.au/pub/media/resized/648x685/blog_images/Cashflow-Banner-Photo.jpg" data-largersrc="https://www.jaybro.com.au/pub/media/resized/648x685/blog_images/Cashflow-Banner-Photo.jpg" src="https://www.jaybro.com.au/pub/media/resized/648x685/blog_images/Cashflow-Banner-Photo.jpg" class="img-responsive  left-block " alt="Cash Flow Bannner">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="col-inner ">
                        <div>
                            <h2 class="w_heading promoHeading">
                                Maximise Cash Flow
                            </h2>
                        </div>
                        <div>
                            <div class="ves-widget widget-html block  ">
                                <div id="widget-html4488658571635659723" class="widget-inner block-content ">
                                    <p class="homePromoText">Online applications approved fast. Buy on 30 days terms and get the products you need, when you need them.</p>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="ves-widget widget-button block homePromoButton ">
                                <div class="widget-inner block-content">
                                    <a href="/about/30-day-trade-account/" class="btn btn-default    action default" title="Apply Now"><i class=""></i>	Apply Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 BtmTwoBxRight">
            <div class="col-inner">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="padding: 0px;">
                    <div class="image-item">
                        <img src="https://www.jaybro.com.au/pub/media/resized/648x685/blog_images/Latest-Catalogue-Banner-Photo.jpg" class="img-responsive  left-block " alt="Latest Catalogue">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="col-inner ">
                            <div>
                                <h2 class="w_heading promoHeading">Latest Catalogue</h2>
                            </div>
                            <div>
                                <div class="ves-widget widget-html block  ">
                                    <div id="widget-html18297033271635659723" class="widget-inner block-content ">
                                        <p class="homePromoText">Jaybro’s latest catalogue, jam-packed with over 360 pages of products for civil and infrastructure contractors</p>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div class="ves-widget widget-button block homePromoButton ">
                                    <div class="widget-inner block-content"><a href="/about/jaybro-catalogue" class="btn btn-default    action default" title="View Now"><i class=""></i>	View Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>